import { getCustomers, saveCustomers, seedCustomers } from "../storage/customerStorage";
import { getBusinesses } from "@/features/business/storage/businessStorage";

const businessId = getBusinesses()[0]?.id || "1";
seedCustomers([
  { id: "customer-1", businessId, customerCode: "CUS-1001", firstName: "Ada", lastName: "Okafor", companyName: "Okafor Trading", displayName: "Ada Okafor", email: "ada@okafortrading.com", phone: "+234 803 111 2222", alternatePhone: "", website: "", address: "14 Marina Road", city: "Lagos", state: "Lagos", country: "Nigeria", postalCode: "101241", taxNumber: "TIN-1001", currency: "NGN", creditLimit: "500000", paymentTerms: "30", status: "active", notes: "Preferred wholesale customer.", avatar: "", createdAt: "2026-08-02", updatedAt: "2026-08-02" },
  { id: "customer-2", businessId, customerCode: "CUS-1002", firstName: "Chidi", lastName: "Eze", companyName: "Eze Foods", displayName: "Chidi Eze", email: "chidi@ezefoods.com", phone: "+234 805 333 4444", alternatePhone: "", website: "", address: "8 Airport Road", city: "Abuja", state: "FCT", country: "Nigeria", postalCode: "900001", taxNumber: "TIN-1002", currency: "NGN", creditLimit: "250000", paymentTerms: "14", status: "active", notes: "", avatar: "", createdAt: "2026-08-03", updatedAt: "2026-08-03" },
  { id: "customer-3", businessId, customerCode: "CUS-1003", firstName: "Fatima", lastName: "Bello", companyName: "Bello Interiors", displayName: "Fatima Bello", email: "fatima@bellointeriors.com", phone: "+234 806 555 6666", alternatePhone: "", website: "", address: "23 Ahmadu Bello Way", city: "Kano", state: "Kano", country: "Nigeria", postalCode: "700001", taxNumber: "TIN-1003", currency: "NGN", creditLimit: "100000", paymentTerms: "7", status: "inactive", notes: "Account under review.", avatar: "", createdAt: "2026-08-04", updatedAt: "2026-08-04" },
  { id: "customer-4", businessId, customerCode: "CUS-1004", firstName: "Tomi", lastName: "Adeyemi", companyName: "Adeyemi Logistics", displayName: "Tomi Adeyemi", email: "tomi@adeyemilogistics.com", phone: "+234 802 777 8888", alternatePhone: "", website: "", address: "5 Ring Road", city: "Ibadan", state: "Oyo", country: "Nigeria", postalCode: "200001", taxNumber: "TIN-1004", currency: "NGN", creditLimit: "750000", paymentTerms: "30", status: "active", notes: "", avatar: "", createdAt: "2026-08-05", updatedAt: "2026-08-05" },
  { id: "customer-5", businessId, customerCode: "CUS-1005", firstName: "Ifeoma", lastName: "Nwosu", companyName: "Nwosu Consulting", displayName: "Ifeoma Nwosu", email: "ifeoma@nwosuconsulting.com", phone: "+234 809 999 0000", alternatePhone: "", website: "", address: "18 Independence Avenue", city: "Enugu", state: "Enugu", country: "Nigeria", postalCode: "400001", taxNumber: "TIN-1005", currency: "NGN", creditLimit: "300000", paymentTerms: "14", status: "active", notes: "", avatar: "", createdAt: "2026-08-06", updatedAt: "2026-08-06" },
]);

export const customerService = {
  async getAll() { return getCustomers(); },
  async getById(id) { return getCustomers().find((customer) => String(customer.id) === String(id)); },
  async create(data) { const customer = { ...data, id: `customer-${Date.now()}`, customerCode: data.customerCode || `CUS-${Date.now().toString().slice(-6)}`, displayName: data.displayName || `${data.firstName} ${data.lastName}`.trim(), createdAt: new Date().toISOString().slice(0, 10), updatedAt: new Date().toISOString().slice(0, 10) }; const customers = getCustomers(); saveCustomers([...customers, customer]); return customer; },
  async update(id, data) { const customers = getCustomers().map((customer) => String(customer.id) === String(id) ? { ...customer, ...data, displayName: data.displayName || `${data.firstName} ${data.lastName}`.trim(), updatedAt: new Date().toISOString().slice(0, 10) } : customer); saveCustomers(customers); return customers.find((customer) => String(customer.id) === String(id)); },
  async delete(id) { saveCustomers(getCustomers().filter((customer) => String(customer.id) !== String(id))); return true; },
};
