import { useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui";
import SessionItemRow from "./SessionItemRow";
export default function SessionItemsTable({ items, products, currency, sessionOptions, sessionIndex, onItemChange, onRemoveItem, onDuplicateItem, onRemoveItems, onDuplicateItems, onMoveItems, onAddItem }) {
  const [selected, setSelected] = useState([]); const [target, setTarget] = useState(""); const selectedSet = new Set(selected); const all = items.length > 0 && selected.length === items.length;
  const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); const clear = () => setSelected([]);
  return <div className="overflow-x-auto p-4">{selected.length > 0 && <div className="mb-3 flex flex-wrap items-center gap-2 rounded-lg bg-slate-100 p-3 text-sm"><b>{selected.length} item{selected.length === 1 ? "" : "s"} selected</b><Button type="button" variant="outline" onClick={() => { onDuplicateItems(selected); clear(); }}>Duplicate</Button>{sessionOptions.length > 1 && <><select aria-label="Move selected items to session" value={target} onChange={(event) => setTarget(event.target.value)} className="rounded border border-slate-300 p-2"><option value="">Move to session…</option>{sessionOptions.map((session, index) => index !== sessionIndex && <option key={session.id} value={index}>{session.title}</option>)}</select><Button type="button" variant="outline" disabled={target === ""} onClick={() => { onMoveItems(target, selected); clear(); setTarget(""); }}>Move</Button></>}<Button type="button" variant="outline" className="text-rose-600" onClick={() => { if (window.confirm(`Delete ${selected.length} selected item${selected.length === 1 ? "" : "s"}?`)) { onRemoveItems(selected); clear(); } }}>Delete</Button></div>}<table className="w-full min-w-[720px] text-sm"><thead className="border-b text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-2"><input aria-label="Select all items" type="checkbox" checked={all} onChange={() => setSelected(all ? [] : items.map((item) => item.id))} /></th>{["Description", "Unit", "Qty", "Unit Price", "Amount"].map((title) => <th key={title} className="p-2">{title}</th>)}<th /></tr></thead><tbody>{items.map((item, index) => <SessionItemRow key={item.id} item={item} index={index} products={products} currency={currency} selected={selectedSet.has(item.id)} onSelect={() => toggle(item.id)} onChange={(field, value) => onItemChange(index, field, value)} onRemove={() => onRemoveItem(index)} onDuplicate={() => onDuplicateItem(index)} />)}</tbody></table><Button type="button" onClick={onAddItem} className="mt-4"><Plus className="mr-2 inline h-4 w-4" />Add Item</Button></div>;
}
