import InvoiceStatusBadge from "@/features/invoices/components/InvoiceStatusBadge";
import ReportDoughnutChart from "./ReportDoughnutChart";

export function InvoiceStatusBreakdown({ breakdown }) {
  const colors = { draft: "#64748B", sent: "#0EA5E9", partially_paid: "#F59E0B", paid: "#10B981", overdue: "#E11D48", cancelled: "#CBD5E1" };
  return <ReportDoughnutChart title="Invoice status" description="Distribution of invoices in this report." centerLabel="invoices" data={breakdown.map((item) => ({ label: item.label, value: item.count, color: colors[item.status] }))} />;
}
export function PaymentCollection({ metrics, formatMoney }) { const invoiced = metrics.revenue + metrics.outstanding; return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Payment collection</h2><p className="mt-1 text-sm text-slate-500">How effectively invoice value is being collected.</p><div className="mt-6"><div className="flex items-end justify-between"><span className="text-3xl font-bold text-[#103746]">{metrics.collectionRate.toFixed(0)}%</span><span className="text-sm text-slate-500">collection rate</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#18566E]" style={{ width: `${metrics.collectionRate}%` }} /></div></div><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Total invoiced</dt><dd className="font-semibold">{formatMoney(invoiced)}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Total collected</dt><dd className="font-semibold text-emerald-700">{formatMoney(metrics.revenue)}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Total outstanding</dt><dd className="font-semibold text-amber-700">{formatMoney(metrics.outstanding)}</dd></div></dl></section>; }

export function TopCustomers({ customers, formatMoney }) { return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><h2 className="font-semibold text-slate-900">Top customers</h2><p className="mt-1 text-sm text-slate-500">Customers ranked by invoice value.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="border-y border-slate-100 bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">Customer</th><th className="px-4 py-3 font-medium">Invoices</th><th className="px-4 py-3 text-right font-medium">Invoiced</th><th className="px-4 py-3 text-right font-medium">Paid</th><th className="px-5 py-3 text-right font-medium">Outstanding</th></tr></thead><tbody>{customers.slice(0, 5).map((item) => <tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4 font-medium text-slate-800">{item.customer?.displayName || "Unknown customer"}</td><td className="px-4 py-4 text-slate-600">{item.invoices}</td><td className="px-4 py-4 text-right">{formatMoney(item.invoiced)}</td><td className="px-4 py-4 text-right text-emerald-700">{formatMoney(item.paid)}</td><td className="px-5 py-4 text-right text-amber-700">{formatMoney(item.outstanding)}</td></tr>)}{!customers.length && <tr><td colSpan="5" className="px-5 py-10 text-center text-slate-500">No customer data for this period.</td></tr>}</tbody></table></div></section>; }

export function RecentTransactions({ transactions, formatMoney, onInvoiceClick }) { return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><h2 className="font-semibold text-slate-900">Recent transactions</h2><p className="mt-1 text-sm text-slate-500">Latest invoices matching the selected filters.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-y border-slate-100 bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">Date</th><th className="px-4 py-3 font-medium">Invoice</th><th className="px-4 py-3 font-medium">Customer</th><th className="px-4 py-3 font-medium">Business</th><th className="px-4 py-3 text-right font-medium">Amount</th><th className="px-4 py-3 text-right font-medium">Paid</th><th className="px-4 py-3 text-right font-medium">Balance</th><th className="px-5 py-3 font-medium">Status</th></tr></thead><tbody>{transactions.slice(0, 8).map((invoice) => <tr onClick={() => onInvoiceClick(invoice.id)} key={invoice.id} className="cursor-pointer border-b border-slate-100 last:border-0 hover:bg-slate-50"><td className="px-5 py-4 text-slate-500">{invoice.issueDate}</td><td className="px-4 py-4 font-medium text-[#103746]">{invoice.invoiceNumber}</td><td className="px-4 py-4">{invoice.customer?.displayName || "Unknown customer"}</td><td className="px-4 py-4 text-slate-600">{invoice.business?.name || "Unknown business"}</td><td className="px-4 py-4 text-right">{formatMoney(invoice.grandTotal)}</td><td className="px-4 py-4 text-right text-emerald-700">{formatMoney(invoice.amountPaid)}</td><td className="px-4 py-4 text-right text-amber-700">{formatMoney(invoice.balance)}</td><td className="px-5 py-4"><InvoiceStatusBadge status={invoice.status} /></td></tr>)}{!transactions.length && <tr><td colSpan="8" className="px-5 py-10 text-center text-slate-500">No transactions match the selected filters.</td></tr>}</tbody></table></div></section>; }

export function ExpenseCategoryChart({ categories, formatMoney }) { const rows = Object.entries(categories).sort((a,b)=>b[1]-a[1]); const total = rows.reduce((sum,[,value])=>sum+value,0); const colors=["#18566E","#14B8A6","#F59E0B","#E11D48","#8B5CF6","#64748B"]; const gradient = total ? `conic-gradient(${rows.map(([category,value,index])=>`${colors[index%colors.length]} ${(rows.slice(0,index).reduce((sum,[,item])=>sum+item,0)/total)*100}% ${(rows.slice(0,index+1).reduce((sum,[,item])=>sum+item,0)/total)*100}%`).join(",")})` : "#e2e8f0"; return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Expense mix</h2><p className="mt-1 text-sm text-slate-500">Cost allocation by expense category.</p>{total?<div className="mt-6 flex flex-col items-center gap-5 sm:flex-row"><div className="grid h-40 w-40 place-items-center rounded-full" style={{background:gradient}}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><b className="text-sm text-slate-800">{formatMoney(total)}</b><span className="text-[10px] text-slate-500">expenses</span></div></div><div className="w-full space-y-2">{rows.slice(0,5).map(([category,value,index])=><div key={category} className="flex justify-between gap-3 text-sm"><span className="flex items-center gap-2 text-slate-600"><i className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:colors[index%colors.length]}}/>{category}</span><b>{formatMoney(value)}</b></div>)}</div></div>:<p className="py-16 text-center text-sm text-slate-500">No expenses in this period.</p>}</section>; }
export function PaymentMethodChart({ methods, formatMoney }) {
  const colors = ["#18566E", "#14B8A6", "#D7B159", "#F97316", "#8B5CF6", "#E11D48"];
  return <ReportDoughnutChart title="Collection channels" description="How customers paid during this period." centerLabel="collected" formatMoney={formatMoney} data={Object.entries(methods).sort((a, b) => b[1] - a[1]).map(([label, value], index) => ({ label, value, color: colors[index % colors.length] }))} />;
}

