import { useEffect, useState } from "react";
import { Download, Printer } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { Breadcrumb, Button, LoadingSkeleton, PageHeader, useToast } from "@/components/ui";
import { getBusinesses } from "@/features/business/storage/businessStorage";
import { getCustomers } from "@/features/customers/storage/customerStorage";
import { QuotationPreview } from "../components";
import { quotationService } from "../services/quotationService";
import { resolveDocumentTheme } from "@/features/documentThemes";
export default function QuotationPreviewPage() { const { id } = useParams(); const navigate = useNavigate(); const toast = useToast(); const [quotation, setQuotation] = useState(null); useEffect(() => { quotationService.getById(id).then((item) => { if (!item) { toast.warning("Quotation not found."); navigate("/quotations"); return; } setQuotation(item); }); }, [id, navigate, toast]); if (!quotation) return <LoadingSkeleton />; const business = getBusinesses().find((item) => String(item.id) === String(quotation.businessId)); const customer = getCustomers().find((item) => String(item.id) === String(quotation.customerId)); const resolvedTheme = resolveDocumentTheme({ business, selectedThemeId: quotation.themeId, document: quotation }); return <div className="space-y-6"><PageHeader title="Quotation Preview" description={quotation.quotationNumber} breadcrumb={<Breadcrumb items={[{ label: "Quotations", href: "/quotations" }, { label: quotation.quotationNumber, href: `/quotations/${id}` }, { label: "Preview" }]} />} actions={<div className="flex gap-2"><Button onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Print</Button><Button onClick={() => toast.info("PDF download will be available in a future release.")}><Download className="mr-2 h-4 w-4" />Download PDF</Button></div>} /><QuotationPreview quotation={quotation} business={business} customer={customer} resolvedTheme={resolvedTheme} printable /></div>; }
