import { useEffect, useMemo, useState } from "react";
import { Button, Modal, ModalBody, ModalFooter } from "@/components/ui";

const methods = ["Bank Transfer", "Cash", "Card", "POS", "Cheque", "Other"];
export default function RecordPaymentModal({ open, invoices = [], customers = [], businesses = [], initialInvoiceId, onClose = () => {}, onSubmit, saving }) {
  const [invoiceId, setInvoiceId] = useState(initialInvoiceId || ""); const [values, setValues] = useState({ paymentDate: new Date().toISOString().slice(0, 10), amount: "", paymentMethod: "Bank Transfer", reference: "", notes: "", receivedBy: "Administrator" }); const [error, setError] = useState("");
  useEffect(() => { if (open) { setInvoiceId(initialInvoiceId || ""); setValues((current) => ({ ...current, amount: "" })); setError(""); } }, [open, initialInvoiceId]);
  const invoice = useMemo(() => invoices.find((item) => String(item.id) === String(invoiceId)), [invoices, invoiceId]); const customer = customers.find((item) => String(item.id) === String(invoice?.customerId)); const business = businesses.find((item) => String(item.id) === String(invoice?.businessId)); const money = (value) => new Intl.NumberFormat("en-NG", { style: "currency", currency: invoice?.currency || business?.currency || "NGN" }).format(Number(value || 0));
  const submit = async (event) => { event.preventDefault(); if (!invoice) return setError("Select an invoice."); const payment = Number(values.amount); if (!payment || payment <= 0) return setError("Enter a payment amount greater than zero."); if (payment > Number(invoice.balance || 0)) return setError("Payment amount cannot exceed the outstanding balance."); setError(""); await onSubmit({ ...values, invoiceId, amount: payment }); };
  const allowed = invoices.filter((item) => !["draft", "cancelled"].includes(item.status) && Number(item.balance) > 0);
  return <Modal open={open} title="Record Payment" onClose={onClose} size="lg"><form onSubmit={submit}><ModalBody><div className="space-y-4"><label className="block text-sm font-medium text-slate-700">Invoice<select value={invoiceId} onChange={(event) => setInvoiceId(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 p-2.5" required><option value="">Select an outstanding invoice</option>{allowed.map((item) => <option key={item.id} value={item.id}>{item.invoiceNumber} â€” {money(item.balance)}</option>)}</select></label>{invoice && <div className="grid gap-3 rounded-xl border border-teal-100 bg-teal-50 p-4 text-sm sm:grid-cols-2"><p><span className="text-slate-500">Customer</span><br /><b>{customer?.displayName || "Unknown customer"}</b></p><p><span className="text-slate-500">Business</span><br /><b>{business?.name || "Unknown business"}</b></p><p><span className="text-slate-500">Invoice total</span><br /><b>{money(invoice.grandTotal)}</b></p><p><span className="text-slate-500">Outstanding balance</span><br /><b className="text-[#103746]">{money(invoice.balance)}</b></p></div>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Payment date"><input type="date" value={values.paymentDate} onChange={(event) => setValues({ ...values, paymentDate: event.target.value })} /></Field><Field label="Amount"><input type="number" min="0.01" max={invoice?.balance || undefined} step="0.01" value={values.amount} onChange={(event) => setValues({ ...values, amount: event.target.value })} placeholder="0.00" /></Field><Field label="Payment method"><select value={values.paymentMethod} onChange={(event) => setValues({ ...values, paymentMethod: event.target.value })}>{methods.map((method) => <option key={method}>{method}</option>)}</select></Field><Field label="Reference number"><input value={values.reference} onChange={(event) => setValues({ ...values, reference: event.target.value })} placeholder="Optional reference" /></Field></div><Field label="Notes"><textarea value={values.notes} onChange={(event) => setValues({ ...values, notes: event.target.value })} rows="3" placeholder="Optional notes" /></Field>{error && <p className="text-sm text-rose-600">{error}</p>}</div></ModalBody><ModalFooter><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Recording..." : "Record Payment"}</Button></ModalFooter></form></Modal>;
}
function Field({ label, children }) { return <label className="block text-sm font-medium text-slate-700">{label}<span className="mt-1 block">{children}</span></label>; }
